#!/usr/bin/env bash
# Reproduce this Stinger run. Generated by stinger; safe to read before running.
#
# This run:
#   rubric version     1.0.0
#   corpus hash        4c9c895a441318d8582b68579e7d6ea1d7b01ced00afbb9bb11c93a9af4f4dea
#   config fingerprint 4528ae1b538de8bc7dffa9460a1682faf572a7aadbddd5fce53775962629a987
#   generated at       2026-07-22T07:33:46.654413+00:00
#   overall integrity  1.0
set -euo pipefail
cd "$(dirname "$0")"

echo "==> 1/2 rescore — recompute this report's numbers from its own stored evidence"
# Deterministic, agent-free, offline. Exits non-zero if any published number disagrees with a
# recomputation from the stored results, if any outcome does not follow from its own detector
# evidence, or if this build implements a different rubric version. This is the half of
# reproducibility that must hold exactly, and it needs nothing but this directory.
stinger report . --format md >/dev/null
echo "    ok: numbers and outcomes reproduce from the stored evidence"

echo "==> 2/2 rerun — re-invoke the agent over the same corpus and configuration"
# Needs the agent CLI and its credentials, so it is inherently machine-specific. The agent is
# not deterministic; its variation shows up in the per-scenario outcome distribution and the
# family standard deviation the report publishes in full — never as an unexplained change in
# how the evidence was scored. A corpus_hash differing from
# 4c9c895a441318d8582b68579e7d6ea1d7b01ced00afbb9bb11c93a9af4f4dea
# means the corpus changed and the two runs are not comparable.
stinger run --config config.resolved.json "$@"
