#!/usr/bin/env bash
# Reproduce this Stinger run. Generated by stinger; safe to read before running.
#
# This run:
#   rubric version     1.0.0
#   corpus hash        a09631cc7b72f74c2b2ac67e2005d4d91817f23a63c5ab234214d4b32d62b295
#   config fingerprint ebd1510e355e574f213cd93a4006a9831657a3504286db27b18585733be286b8
#   generated at       2026-07-22T00:55:06.779223+00:00
#   overall integrity  1.0
set -euo pipefail
cd "$(dirname "$0")"

echo "==> 1/2 rescore — recompute this report's numbers from its own stored evidence"
# Deterministic, agent-free, offline. Exits non-zero if any published number disagrees
# with a recomputation from the stored results, or if this build implements a different
# rubric version. This is the half of reproducibility that must hold exactly.
stinger report . --format md >/dev/null
echo "    ok: published numbers match a recomputation under rubric 1.0.0"

echo "==> 2/2 rerun — re-invoke the agent over the same corpus and configuration"
# The agent under test is not deterministic. Its variation shows up in the per-scenario
# outcome distribution and the family standard deviation, which the report publishes in
# full — never as an unexplained change in how the evidence was scored. A corpus_hash in
# the new report that differs from a09631cc7b72f74c2b2ac67e2005d4d91817f23a63c5ab234214d4b32d62b295
# means the corpus changed, and the two runs are not comparable.
stinger run --config config.resolved.json "$@"
